name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - ruby: 3.0
          gemfile: Gemfile
        - ruby: 3.0
          gemfile: gemfiles/activerecord61.gemfile
        - ruby: 2.7
          gemfile: gemfiles/activerecord60.gemfile
        - ruby: 2.6
          gemfile: gemfiles/activerecord52.gemfile
        - ruby: 2.5
          gemfile: gemfiles/activerecord51.gemfile
        - ruby: 2.4
          gemfile: gemfiles/activerecord50.gemfile
        - ruby: 2.7
          gemfile: gemfiles/mongoid7.gemfile
          mongodb: true
        - ruby: 2.6
          gemfile: gemfiles/mongoid6.gemfile
          mongodb: true
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - if: ${{ matrix.mongodb }}
      uses: ankane/setup-mongodb@v1
    - run: bundle exec rake test
