name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 3.4
            gemfile: Gemfile
          - ruby: 3.3
            gemfile: gemfiles/activerecord72.gemfile
          - ruby: 3.2
            gemfile: gemfiles/activerecord71.gemfile
          - ruby: 3.3
            gemfile: gemfiles/mongoid9.gemfile
            mongodb: true
          - ruby: 3.2
            gemfile: gemfiles/mongoid8.gemfile
            mongodb: true
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - if: ${{ matrix.mongodb }}
        uses: ankane/setup-mongodb@v1
      - run: bundle exec rake test
